jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      linux_c_compilergccfortran_compilergfortranmpimpichtarget_platformlinux-64:
        CONFIG: linux_c_compilergccfortran_compilergfortranmpimpichtarget_platformlinux-64
      linux_c_compilergccfortran_compilergfortranmpinompitarget_platformlinux-64:
        CONFIG: linux_c_compilergccfortran_compilergfortranmpinompitarget_platformlinux-64
      linux_c_compilergccfortran_compilergfortranmpiopenmpitarget_platformlinux-64:
        CONFIG: linux_c_compilergccfortran_compilergfortranmpiopenmpitarget_platformlinux-64
      linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpimpichtarget_platformlinux-64:
        CONFIG: linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpimpichtarget_platformlinux-64
      linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpinompitarget_platformlinux-64:
        CONFIG: linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpinompitarget_platformlinux-64
      linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpiopenmpitarget_platformlinux-64:
        CONFIG: linux_c_compilertoolchain_cfortran_compilertoolchain_fortmpiopenmpitarget_platformlinux-64
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build